-- ==========================================
-- 1. CREACIÓN DE LA TABLA 'operadores'
-- ==========================================
CREATE TABLE IF NOT EXISTS public.operadores (
    id_perfil int8 PRIMARY KEY,
    nombre_real text NOT NULL,
    agencia text,
    estado text DEFAULT 'Activo',
    fecha_ingreso date DEFAULT CURRENT_DATE
);

-- Habilitar Políticas de Seguridad a Nivel de Fila (RLS)
ALTER TABLE public.operadores ENABLE ROW LEVEL SECURITY;

-- Permiso de lectura pública para que index.html pueda mostrar los nombres en el Ranking
DROP POLICY IF EXISTS "Permitir lectura publica a operadores" ON public.operadores;
CREATE POLICY "Permitir lectura publica a operadores" 
    ON public.operadores 
    FOR SELECT 
    USING (true);

-- Permiso para que el administrador pueda editar, actualizar e insertar desde la UI o directamente
DROP POLICY IF EXISTS "Permitir edición a todos los roles" ON public.operadores;
CREATE POLICY "Permitir edición a todos los roles" 
    ON public.operadores 
    FOR ALL 
    USING (true)
    WITH CHECK (true);

-- ===========================================================
-- INSERCIÃ“N FINAL DE OPERADORES (CONCRUCE DE IDs DE NOVEDADES)
-- ===========================================================

INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91733663, 'EDWIN JOSE ROMERO FERRER', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (79679899, 'EDWIN JOSE ROMERO FERRER', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143014129, 'JOSE GREGORIO MENDEZ NOGUERA', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145211163, 'JOSE GREGORIO MENDEZ NOGUERA', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143017065, 'JOSE GREGORIO MENDEZ NOGUERA', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (79679899, 'JOSE GREGORIO MENDEZ NOGUERA', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91733663, 'JOSE GREGORIO MENDEZ NOGUERA', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (88243516, 'JUAN CARLOS RODRIGUEZ RODRÃGUEZ', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91360720, 'JUAN CARLOS RODRIGUEZ RODRÃGUEZ', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95956014, 'JUAN CARLOS RODRIGUEZ RODRÃGUEZ', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130338853, 'YHONGERVIS JESUS AVILA JIMENEZ', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118179794, 'YHONGERVIS JESUS AVILA JIMENEZ', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (137163229, 'YHONGERVIS JESUS AVILA JIMENEZ', 'Amolatina', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145844971, 'EDUARD JOSUE RICO ZAMBRANO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145834230, 'EDUARD JOSUE RICO ZAMBRANO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (144863124, 'EDUARD JOSUE RICO ZAMBRANO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98389135, 'JESUS ALBERTO LEON VALENCIA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139247498, 'JESUS ALBERTO LEON VALENCIA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120720195, 'JESUS ALBERTO LEON VALENCIA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118404407, 'JUAN CAMILO CARVAJAL FLOREZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103291980, 'JUAN CAMILO CARVAJAL FLOREZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130431310, 'JUAN CAMILO CARVAJAL FLOREZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98540781, 'JUAN CAMILO CARVAJAL FLOREZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118404407, 'JUAN CAMILO CARVAJAL FLOREZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103291980, 'JUAN CAMILO CARVAJAL FLOREZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130431310, 'JUAN CAMILO CARVAJAL FLOREZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98540781, 'JUAN CAMILO CARVAJAL FLOREZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95955130, 'KEVIN SEBASTIAN BARON AVILA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103289167, 'KEVIN SEBASTIAN BARON AVILA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (108018336, 'KEVIN SEBASTIAN BARON AVILA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145844971, 'KRISTAL CASTRO MONTILLA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145834230, 'KRISTAL CASTRO MONTILLA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (144863124, 'KRISTAL CASTRO MONTILLA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143014129, 'LUIS FELIPE NOVOA MENDOZA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143017065, 'LUIS FELIPE NOVOA MENDOZA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145211163, 'LUIS FELIPE NOVOA MENDOZA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (133085188, 'MARIA FERNANDA CHALITA HERNANDEZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (138130329, 'MARIA FERNANDA CHALITA HERNANDEZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (132062039, 'MARIA FERNANDA CHALITA HERNANDEZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130338853, 'OSCAR JOSE GOMEZ GUERRA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118179794, 'OSCAR JOSE GOMEZ GUERRA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (137163229, 'OSCAR JOSE GOMEZ GUERRA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91733663, 'ANDREINA DE LOS ANGELES YSSA MORENO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (79679899, 'ANDREINA DE LOS ANGELES YSSA MORENO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91733663, 'ANAZARED RODRIGUEZ CAMPOS', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (79679899, 'ANAZARED RODRIGUEZ CAMPOS', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91733663, 'ANDREINA DE LOS ANGELES YSSA MORENO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (79679899, 'ANDREINA DE LOS ANGELES YSSA MORENO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (79679899, 'BORIS JUVENAL PATIÃ‘O ESCORIHUELA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91733663, 'BORIS JUVENAL PATIÃ‘O ESCORIHUELA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118179794, 'BORIS JUVENAL PATIÃ‘O ESCORIHUELA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130338853, 'BORIS JUVENAL PATIÃ‘O ESCORIHUELA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (137163229, 'BORIS JUVENAL PATIÃ‘O ESCORIHUELA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98389135, 'JESUS DAVID CASTAÃ‘EDA ROJAS', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139247498, 'JESUS DAVID CASTAÃ‘EDA ROJAS', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120720195, 'JESUS DAVID CASTAÃ‘EDA ROJAS', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118404407, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103291980, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130431310, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98540781, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118404407, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103291980, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130431310, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98540781, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (133085188, 'BRANDON MIGUEL FERNANDEZ MORA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (138130329, 'BRANDON MIGUEL FERNANDEZ MORA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (132062039, 'BRANDON MIGUEL FERNANDEZ MORA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95955130, 'BRIGITH DE LOS ANGELES FERNANDEZ MORA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103289167, 'BRIGITH DE LOS ANGELES FERNANDEZ MORA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (108018336, 'BRIGITH DE LOS ANGELES FERNANDEZ MORA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118692242, 'CATHERINE NAOMI FIGUEREDO HERNANDEZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (109551682, 'CATHERINE NAOMI FIGUEREDO HERNANDEZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (131130713, 'CATHERINE NAOMI FIGUEREDO HERNANDEZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143014129, 'EDUIN JOSE ESPAÃ‘A DIAZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143017065, 'EDUIN JOSE ESPAÃ‘A DIAZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145211163, 'EDUIN JOSE ESPAÃ‘A DIAZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95955130, 'ESPERANZA JIMENEZ SEVILLA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103289167, 'ESPERANZA JIMENEZ SEVILLA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120720195, 'ESPERANZA JIMENEZ SEVILLA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (108018336, 'ESPERANZA JIMENEZ SEVILLA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98389135, 'FREDERYCK JOSE GALICIA CAMARIPANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139247498, 'FREDERYCK JOSE GALICIA CAMARIPANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120720195, 'FREDERYCK JOSE GALICIA CAMARIPANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118404407, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103291980, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130431310, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98540781, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118404407, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103291980, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130431310, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98540781, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (88243516, 'GABRIEL LUISDEVIT GONZALEZ ARCIA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91360720, 'GABRIEL LUISDEVIT GONZALEZ ARCIA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95956014, 'GABRIEL LUISDEVIT GONZALEZ ARCIA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98389135, 'JESUS ALBERTO AVILA BELISARIO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139247498, 'JESUS ALBERTO AVILA BELISARIO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120720195, 'JESUS ALBERTO AVILA BELISARIO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98389135, 'JESUS DAVID PAJARO PIÃ‘ERES', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139247498, 'JESUS DAVID PAJARO PIÃ‘ERES', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120720195, 'JESUS DAVID PAJARO PIÃ‘ERES', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (88243516, 'JHORIANNYS ESTHER MOSQUERA ROJANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91360720, 'JHORIANNYS ESTHER MOSQUERA ROJANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95956014, 'JHORIANNYS ESTHER MOSQUERA ROJANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118692242, 'JOSE MANUEL VARELA LEON', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (109551682, 'JOSE MANUEL VARELA LEON', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (131130713, 'JOSE MANUEL VARELA LEON', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120275229, 'JOSUE DAVID HENRIQUEZ REGALADO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130422416, 'JOSUE DAVID HENRIQUEZ REGALADO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (101652076, 'JOSUE DAVID HENRIQUEZ REGALADO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139245989, 'JOSUE DAVID HENRIQUEZ REGALADO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118404407, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103291980, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130431310, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98540781, 'JUAN CAMILO RINCON PIRAVAGUEN', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (88243516, 'JUAN CARLOS MORENO GUERRA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91360720, 'JUAN CARLOS MORENO GUERRA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95956014, 'JUAN CARLOS MORENO GUERRA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95955130, 'KEVIN SEBASTIAN BARON AVILA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103289167, 'KEVIN SEBASTIAN BARON AVILA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (108018336, 'KEVIN SEBASTIAN BARON AVILA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145844971, 'KRYSTAL GABRIELA CASTRO MONTILLA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145834230, 'KRYSTAL GABRIELA CASTRO MONTILLA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (144863124, 'KRYSTAL GABRIELA CASTRO MONTILLA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (133085188, 'MARIA FERNANDA MANCERA SILVA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (138130329, 'MARIA FERNANDA MANCERA SILVA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (132062039, 'MARIA FERNANDA MANCERA SILVA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118404407, 'MARYULIS YUSMARIS ARIAS ARIAS', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103291980, 'MARYULIS YUSMARIS ARIAS ARIAS', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130431310, 'MARYULIS YUSMARIS ARIAS ARIAS', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98540781, 'MARYULIS YUSMARIS ARIAS ARIAS', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130338853, 'OSCAR JOSE GOMEZ GUERRA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118179794, 'OSCAR JOSE GOMEZ GUERRA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (137163229, 'OSCAR JOSE GOMEZ GUERRA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118692242, 'SKERLY NAILEX VALERO BRICEÃ‘O', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (109551682, 'SKERLY NAILEX VALERO BRICEÃ‘O', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (131130713, 'SKERLY NAILEX VALERO BRICEÃ‘O', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118404407, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103291980, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130431310, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98540781, 'WILLIANNYS DEL VALLE GUZMAN ANGULO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (133085188, 'YARELIS ESTHER SEVILLA PADILLA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (138130329, 'YARELIS ESTHER SEVILLA PADILLA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (132062039, 'YARELIS ESTHER SEVILLA PADILLA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130338853, 'YHONGERVIS JESUS AVILA JIMENEZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118179794, 'YHONGERVIS JESUS AVILA JIMENEZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (137163229, 'YHONGERVIS JESUS AVILA JIMENEZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (88243516, 'GABRIEL LUISDEVIT GONZALEZ ARCIA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91360720, 'GABRIEL LUISDEVIT GONZALEZ ARCIA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95956014, 'GABRIEL LUISDEVIT GONZALEZ ARCIA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (133085188, 'BRANDON MIGUEL FERNANDEZ MORA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (138130329, 'BRANDON MIGUEL FERNANDEZ MORA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (132062039, 'BRANDON MIGUEL FERNANDEZ MORA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145844971, 'ALEIKA ALEJANDRA PERALTA MENDOZA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145834230, 'ALEIKA ALEJANDRA PERALTA MENDOZA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (144863124, 'ALEIKA ALEJANDRA PERALTA MENDOZA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98389135, 'FREDERYCK JOSE GALICIA CAMARIPANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139247498, 'FREDERYCK JOSE GALICIA CAMARIPANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120720195, 'FREDERYCK JOSE GALICIA CAMARIPANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120275229, 'ANDRI JOSUE CALDERON PEREZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130422416, 'ANDRI JOSUE CALDERON PEREZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (101652076, 'ANDRI JOSUE CALDERON PEREZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139245989, 'ANDRI JOSUE CALDERON PEREZ', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143014129, 'JHONNYS ISAC GONZALEZ REQUENA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143017065, 'JHONNYS ISAC GONZALEZ REQUENA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145211163, 'JHONNYS ISAC GONZALEZ REQUENA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143014129, 'JOSE GREGORIO ESCALA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145211163, 'JOSE GREGORIO ESCALA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143017065, 'JOSE GREGORIO ESCALA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (79679899, 'JOSE GREGORIO ESCALA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91733663, 'JOSE GREGORIO ESCALA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143014129, 'VERONICA YOLYANA PATIÃ‘O ESCORIHUELA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143017065, 'VERONICA YOLYANA PATIÃ‘O ESCORIHUELA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145211163, 'VERONICA YOLYANA PATIÃ‘O ESCORIHUELA', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145844971, 'EDUARD JOSUE RICO ZAMBRANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145834230, 'EDUARD JOSUE RICO ZAMBRANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (144863124, 'EDUARD JOSUE RICO ZAMBRANO', 'Talkytimes', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120275229, 'CARLOS MOISES RODRIGUEZ MENDOZA', 'Talkytimes Camilo', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130422416, 'CARLOS MOISES RODRIGUEZ MENDOZA', 'Talkytimes Camilo', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (101652076, 'CARLOS MOISES RODRIGUEZ MENDOZA', 'Talkytimes Camilo', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139245989, 'CARLOS MOISES RODRIGUEZ MENDOZA', 'Talkytimes Camilo', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (88243516, 'JUAN CARLOS RODRIGUEZ RODRÃGUEZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91360720, 'JUAN CARLOS RODRIGUEZ RODRÃGUEZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95956014, 'JUAN CARLOS RODRIGUEZ RODRÃGUEZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145844971, 'KRYSTAL GABRIELA CASTRO MONTILLA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145834230, 'KRYSTAL GABRIELA CASTRO MONTILLA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (144863124, 'KRYSTAL GABRIELA CASTRO MONTILLA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91733663, 'ANAZARED RODRIGUEZ CAMPOS', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (79679899, 'ANAZARED RODRIGUEZ CAMPOS', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95955130, 'BRIGITH DE LOS ANGELES FERNANDEZ MORA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103289167, 'BRIGITH DE LOS ANGELES FERNANDEZ MORA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (108018336, 'BRIGITH DE LOS ANGELES FERNANDEZ MORA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95955130, 'ESPERANZA JIMENEZ SEVILLA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103289167, 'ESPERANZA JIMENEZ SEVILLA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120720195, 'ESPERANZA JIMENEZ SEVILLA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (108018336, 'ESPERANZA JIMENEZ SEVILLA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (88243516, 'JHORIANNYS ESTHER MOSQUERA ROJANO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91360720, 'JHORIANNYS ESTHER MOSQUERA ROJANO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95956014, 'JHORIANNYS ESTHER MOSQUERA ROJANO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95955130, 'KEVIN SEBASTIAN BARON AVILA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103289167, 'KEVIN SEBASTIAN BARON AVILA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (108018336, 'KEVIN SEBASTIAN BARON AVILA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118692242, 'SKERLY NAILEX VALERO BRICEÃ‘O', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (109551682, 'SKERLY NAILEX VALERO BRICEÃ‘O', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (131130713, 'SKERLY NAILEX VALERO BRICEÃ‘O', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143014129, 'EDUIN JOSE ESPAÃ‘A DIAZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (143017065, 'EDUIN JOSE ESPAÃ‘A DIAZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (145211163, 'EDUIN JOSE ESPAÃ‘A DIAZ', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (88243516, 'GABRIEL LUISDEVIT GONZALEZ ARCIA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (91360720, 'GABRIEL LUISDEVIT GONZALEZ ARCIA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (95956014, 'GABRIEL LUISDEVIT GONZALEZ ARCIA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98389135, 'JESUS ALBERTO AVILA BELISARIO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139247498, 'JESUS ALBERTO AVILA BELISARIO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120720195, 'JESUS ALBERTO AVILA BELISARIO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120275229, 'JOSUE DAVID HENRIQUEZ REGALADO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130422416, 'JOSUE DAVID HENRIQUEZ REGALADO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (101652076, 'JOSUE DAVID HENRIQUEZ REGALADO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139245989, 'JOSUE DAVID HENRIQUEZ REGALADO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (133085188, 'BRANDON MIGUEL FERNANDEZ MORA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (138130329, 'BRANDON MIGUEL FERNANDEZ MORA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (132062039, 'BRANDON MIGUEL FERNANDEZ MORA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118404407, 'MARYULIS YUSMARIS ARIAS ARIAS', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (103291980, 'MARYULIS YUSMARIS ARIAS ARIAS', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130431310, 'MARYULIS YUSMARIS ARIAS ARIAS', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98540781, 'MARYULIS YUSMARIS ARIAS ARIAS', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (130338853, 'OSCAR JOSE GOMEZ GUERRA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (118179794, 'OSCAR JOSE GOMEZ GUERRA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (137163229, 'OSCAR JOSE GOMEZ GUERRA', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (98389135, 'FREDERYCK JOSE GALICIA CAMARIPANO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (139247498, 'FREDERYCK JOSE GALICIA CAMARIPANO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
INSERT INTO public.operadores (id_perfil, nombre_real, agencia, estado) VALUES (120720195, 'FREDERYCK JOSE GALICIA CAMARIPANO', 'General', 'Activo') ON CONFLICT (id_perfil) DO UPDATE SET nombre_real = EXCLUDED.nombre_real, agencia = EXCLUDED.agencia;
